### ISSUE TITLE
Exception while using special characters in expression value

### ISSUE THREAD

**Issue by vijendrasainimetacube** [jaystack/odata-v4-mongodb#15]
Hi,
I am getting exception while using '/' in expression value. for example:

var query = createQuery("$filter=status ne 'FIXED/RESOLVED'");

Error: Unexpected character at 14$filter=status ne 'FIXED/RESOLVED'
    at D:\workspace\AmeriGas\API-Server\api-server\node_modules\odata-v4-parser\lib\parser.js:25:19
    at Object.query (D:\workspace\AmeriGas\API-Server\api-server\node_modules\odata-v4-parser\lib\parser.js:45:93)
    at createQuery (D:\workspace\AmeriGas\API-Server\api-server\node_modules\odata-v4-mongodb\lib\index.js:6:66)

Thanks

**Comment by MathieuCouette** [comment]
It's somewhat complicated, but my understanding is that the module expects the parameter names (`$filter`, in this case) and the parameter values (`status ne 'FIXED/RESOLVED'`, in this case) [to be URI encoded](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752335). You can use [`encodeURIComponent` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to do that.

Keep in mind that the module currently has a bug that prevents the usage of URI encoded date times.

**Comment by WandererInVoids** [comment]
i create package with fix 
https://github.com/WandererInVoids/odata-v4-mongodb 
https://www.npmjs.com/package/@wandererin/odata-v4-mongodb
